In [1]:
!pip install wrds

Collecting wrds
  Downloading wrds-3.0.8-py3-none-any.whl (12 kB)
Requirement already satisfied: mock in c:\users\jamhouse\anaconda3\lib\site-packages (from wrds) (4.0.2)
Requirement already satisfied: sqlalchemy in c:\users\jamhouse\anaconda3\lib\site-packages (from wrds) (1.3.18)
Requirement already satisfied: pandas in c:\users\jamhouse\anaconda3\lib\site-packages (from wrds) (1.0.5)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.8.6-cp38-cp38-win_amd64.whl (1.1 MB)
Requirement already satisfied: numpy>=1.13.3 in c:\users\jamhouse\anaconda3\lib\site-packages (from pandas->wrds) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in c:\users\jamhouse\anaconda3\lib\site-packages (from pandas->wrds) (2020.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\jamhouse\anaconda3\lib\site-packages (from pandas->wrds) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\jamhouse\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas->wrds) (1.15.0)
Installing collected packages: psycopg2-binary, wrds
Successfully installed psycopg2-binary-2.8.6 wrds-3.0.8

In [6]:
import wrds

In [7]:
db = wrds.Connection()

Enter your WRDS username [JAMHouse]:jose84
Enter your password:········
WRDS recommends setting up a .pgpass file.
You can find more info here:
https://www.postgresql.org/docs/9.5/static/libpq-pgpass.html.
Loading library list...
Done

In [8]:
db.list_libraries()

['aha',
 'aha_sample',
 'ahasamp',
 'audit',
 'audit_audit_comp',
 'audit_corp_legal',
 'auditsmp',
 'bank',
 'blab',
 'block',
 'block_all_new',
 'boardex',
 'boardex_eur',
 'boardex_na',
 'boardex_row',
 'boardex_trial',
 'boardex_uk',
 'boardsmp',
 'bvd',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'cboe',
 'centris',
 'ciq',
 'ciqsamp',
 'ciqsamp_common',
 'ciqsamp_transcripts',
 'cisdm',
 'cisdmsmp',
 'comp',
 'comp_bank',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_global',
 'comp_global_daily',
 'comp_segments_hist',
 'comp_segments_hist_daily',
 'compa',
 'compb',
 'compbd',
 'compdcur',
 'compg',
 'compgd',
 'comph',
 'compm',
 'compmcur',
 'compnad',
 'compsamp',
 'compsamp_snapshot',
 'compseg',
 'compsegd',
 'compsnap',
 'comscore',
 'contrib',
 'contrib_ceo_turnover',
 'contrib_char_returns',
 'contrib_general',
 'contrib_general_new',
 'contrib_intangible_value',
 'contrib_kpss',
 'contrib_liva',
 'crsp',
 'crsp_a_ccm',
 'crsp_a_indexes',
 'crsp_a_stock',
 'crsp_a_stock_new',
 'crsp_a_treasuries',
 'crsp_q_indexhist',
 'crsp_q_mutualfunds',
 'crsp_q_mutualfunds_new',
 'crspa',
 'crspm',
 'crspq',
 'crspsamp',
 'csmar',
 'dealscan',
 'djones',
 'dmef',
 'doe',
 'emdb',
 'etfg',
 'etfg_samp',
 'etfgsamp',
 'eureka',
 'eurekahedge_sample',
 'eursamp',
 'evts',
 'execcomp',
 'factsamp_revere',
 'factset',
 'factset_revere_supply_chain',
 'ff',
 'fisd',
 'fisdsamp',
 'fjc',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'fssamp',
 'ftse',
 'ftsesamp',
 'ginsight',
 'gmi',
 'govpx',
 'govpx_common',
 'govpx_common_new',
 'govpx_ticks1991',
 'govpx_ticks1992',
 'govpx_ticks1993',
 'govpx_ticks1994',
 'govpx_ticks1995',
 'govpx_ticks1996',
 'govpx_ticks1997',
 'govpx_ticks1998',
 'govpx_ticks1999',
 'govpx_ticks2000',
 'govpxsmp',
 'gsi',
 'hbase_sample',
 'hbsamp',
 'hfr',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibes',
 'ibescorp',
 'ibeskpi',
 'ifgr',
 'ifgrsamp',
 'ims',
 'ims_obp_trial',
 'imssamp',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'iri',
 'iss',
 'issm',
 'kld',
 'kld_histall',
 'ktmine',
 'ktmine_patents_samp',
 'ktsamp',
 'levin',
 'lspd',
 'lspdsamp',
 'lvnsamp',
 'macrofin',
 'macrofin_comm_trade',
 'macrofin_comm_trade_new',
 'markit',
 'markit_cds',
 'mfl',
 'midas',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'msfanly',
 'msfinst',
 'msrb',
 'msrbsamp',
 'nastraq',
 'omtrial',
 'optionm',
 'optionm_all_new',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'pacap',
 'phlx',
 'ppublica',
 'ppubsamp',
 'ppubsamp_d4d',
 'ppubsamp_d4d_new',
 'preqin',
 'preqsamp',
 'preqsamp_all_new',
 'public',
 'pwt',
 'ravenpack_trial',
 'rent',
 'reprisk',
 'reprisk_sample',
 'repsamp',
 'revere',
 'risk',
 'risk_directors',
 'risk_governance',
 'risk_proposals',
 'risk_votes',
 'risksamp',
 'rpa',
 'rpna',
 'rpnasamp',
 'sdc',
 'sdcsamp',
 'secsamp',
 'secsamp_all_new',
 'snapsamp',
 'snl',
 'snlsamp',
 'snlsamp_fig',
 'sprat',
 'sustain',
 'sustsamp',
 'taq',
 'taqm_2010',
 'taqm_2011',
 'taqm_2012',
 'taqm_2013',
 'taqm_2014',
 'taqm_2015',
 'taqm_2016',
 'taqm_2017',
 'taqm_2018',
 'taqm_2019',
 'taqm_2020',
 'taqmsamp',
 'taqmsec',
 'taqsamp',
 'tass',
 'tfn',
 'totalq',
 'totalq_all_new',
 'toyo',
 'toyosamp',
 'tr_13f',
 'tr_dealscan',
 'tr_ds',
 'tr_ibes',
 'tr_ibes_guidance',
 'tr_insiders',
 'tr_mutualfunds',
 'tr_ownership',
 'tr_tass',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trdssamp',
 'trdstrm',
 'tresg',
 'trown',
 'trsamp',
 'trsdcgs',
 'trws',
 'twoiq',
 'twoiq_samp',
 'twoiqsmp',
 'wcai',
 'wqa',
 'wrds_lib_internal',
 'wrdsapps',
 'wrdsapps_eushort',
 'wrdsapps_eushort_new',
 'wrdsapps_evtstudy_lr',
 'wrdsapps_evtstudy_lr_new',
 'wrdsapps_finratio',
 'wrdsapps_finratio_ccm',
 'wrdsapps_finratio_ibes',
 'wrdsapps_finratio_ibes_ccm',
 'wrdsapps_finratio_new',
 'wrdsapps_link_crsp_ibes',
 'wrdsapps_link_crsp_ibes_new',
 'wrdsapps_patents',
 'wrdsapps_patents_new',
 'wrdsapps_windices',
 'wrdsrpts',
 'wrdsrpts_rep_usage',
 'wrdssec',
 'wrdssec_common',
 'wrdssec_insiders',
 'wrdssec_midas',
 'wrdssec_midas_new',
 'wrdssec_secsa',
 'zacks',
 'zacksamp']

In [9]:
db.list_tables(library='crsp')

['acti',
 'asia',
 'asib',
 'asic',
 'asio',
 'asix',
 'bmdebt',
 'bmheader',
 'bmpaymts',
 'bmquotes',
 'bmyield',
 'bndprt06',
 'bndprt12',
 'bxcalind',
 'bxdlyind',
 'bxmthind',
 'bxquotes',
 'bxyield',
 'cap',
 'ccm_lookup',
 'ccm_qvards',
 'ccmxpf_linktable',
 'ccmxpf_lnkhist',
 'ccmxpf_lnkrng',
 'ccmxpf_lnkused',
 'comphead',
 'comphist',
 'compmaster',
 'contact_info',
 'crsp_cik_map',
 'crsp_daily_data',
 'crsp_header',
 'crsp_monthly_data',
 'crsp_names',
 'crsp_portno_map',
 'crsp_ziman_daily_index',
 'crsp_ziman_monthly_index',
 'cs20yr',
 'cs5yr',
 'cs90d',
 'cst_hist',
 'daily_nav',
 'daily_nav_ret',
 'daily_returns',
 'dividends',
 'dport1',
 'dport2',
 'dport3',
 'dport4',
 'dport5',
 'dport6',
 'dport7',
 'dport8',
 'dport9',
 'dsbc',
 'dsbo',
 'dse',
 'dse62',
 'dse62delist',
 'dse62dist',
 'dse62exchdates',
 'dse62names',
 'dse62nasdin',
 'dse62shares',
 'dseall',
 'dseall62',
 'dsedelist',
 'dsedist',
 'dseexchdates',
 'dsenames',
 'dsenasdin',
 'dseshares',
 'dsf',
 'dsf62',
 'dsfhdr',
 'dsfhdr62',
 'dsi',
 'dsi62',
 'dsia',
 'dsib',
 'dsic',
 'dsio',
 'dsir',
 'dsix',
 'dsiy',
 'dsp500',
 'dsp500list',
 'dsp500p',
 'dssc',
 'dsso',
 'eod_cap',
 'eod_sector',
 'eod_vg',
 'erdport1',
 'erdport2',
 'erdport3',
 'erdport4',
 'erdport5',
 'erdport6',
 'erdport7',
 'erdport8',
 'erdport9',
 'ermport1',
 'ermport2',
 'ermport3',
 'ermport4',
 'ermport5',
 'fbpri',
 'fbyld',
 'front_load',
 'front_load_det',
 'front_load_grp',
 'fund_fees',
 'fund_flows',
 'fund_hdr',
 'fund_hdr_hist',
 'fund_names',
 'fund_style',
 'fund_summary',
 'fund_summary2',
 'fwdask06',
 'fwdask12',
 'fwdave06',
 'fwdave12',
 'fwdbid06',
 'fwdbid12',
 'hldask06',
 'hldask12',
 'hldave06',
 'hldave12',
 'hldbid06',
 'hldbid12',
 'holdings',
 'index_descriptions',
 'index_type_map',
 'mbi',
 'mbmdat',
 'mbmhdr',
 'mbx',
 'mbxid',
 'mcti',
 'mfdbname',
 'mhista',
 'mhistn',
 'mhistq',
 'monthly_nav',
 'monthly_returns',
 'monthly_tna',
 'monthly_tna_ret_nav',
 'mport1',
 'mport2',
 'mport3',
 'mport4',
 'mport5',
 'mse',
 'mse62',
 'mse62delist',
 'mse62dist',
 'mse62exchdates',
 'mse62names',
 'mse62nasdin',
 'mse62shares',
 'mseall',
 'mseall62',
 'msedelist',
 'msedist',
 'mseexchdates',
 'msenames',
 'msenasdin',
 'mseshares',
 'msf',
 'msf62',
 'msfhdr',
 'msfhdr62',
 'msi',
 'msi62',
 'msia',
 'msib',
 'msic',
 'msio',
 'msir',
 'msix',
 'msiy',
 'msp500',
 'msp500list',
 'msp500p',
 'portnomap',
 'priask06',
 'priask12',
 'priave06',
 'priave12',
 'pribid06',
 'pribid12',
 'price_type',
 'property_type',
 'qcti',
 'qsia',
 'qsib',
 'qsic',
 'qsio',
 'qsix',
 'rear_load',
 'rear_load_det',
 'rear_load_grp',
 'rebala',
 'rebaln',
 'rebalq',
 'reit_type',
 'riskfree',
 's6z_agg_ann',
 's6z_agg_mth',
 's6z_agg_qtr',
 's6z_del',
 's6z_dind',
 's6z_dis',
 's6z_dp_dly',
 's6z_ds_dly',
 's6z_hdr',
 's6z_indhdr',
 's6z_mdel',
 's6z_mind',
 's6z_mth',
 's6z_nam',
 's6z_ndi',
 's6z_shr',
 'saz_agg_ann',
 'saz_agg_mth',
 'saz_agg_qtr',
 'saz_del',
 'saz_dind',
 'saz_dis',
 'saz_dp_dly',
 'saz_ds_dly',
 'saz_hdr',
 'saz_indhdr',
 'saz_mdel',
 'saz_mind',
 'saz_mth',
 'saz_nam',
 'saz_ndi',
 'saz_shr',
 'sechead',
 'sechist',
 'sector',
 'sfz_dind',
 'sfz_indhdr',
 'sfz_mbr',
 'sfz_mind',
 'sfz_portd',
 'sfz_portm',
 'sfz_rb',
 'stock_qvards',
 'stocknames',
 'stocknames62',
 'sub_property_type',
 'tfz_dly',
 'tfz_dly_cd',
 'tfz_dly_cpi',
 'tfz_dly_ft',
 'tfz_dly_rf2',
 'tfz_dly_ts2',
 'tfz_idx',
 'tfz_iss',
 'tfz_mast',
 'tfz_mth',
 'tfz_mth_bp',
 'tfz_mth_cd',
 'tfz_mth_cpi',
 'tfz_mth_fb',
 'tfz_mth_ft',
 'tfz_mth_rf',
 'tfz_mth_rf2',
 'tfz_mth_ts',
 'tfz_mth_ts2',
 'tfz_pay',
 'vg',
 'yldask06',
 'yldask12',
 'yldave06',
 'yldave12',
 'yldbid06',
 'yldbid12',
 'ziman_reit_info',
 'zr_hdrnames']

In [10]:
db.describe_table(library='crsp', table='msi')

Approximately 1141 rows in crsp.msi.

      name  nullable              type
0     date      True              DATE
1   vwretd      True  DOUBLE PRECISION
2   vwretx      True  DOUBLE PRECISION
3   ewretd      True  DOUBLE PRECISION
4   ewretx      True  DOUBLE PRECISION
5   sprtrn      True  DOUBLE PRECISION
6   spindx      True  DOUBLE PRECISION
7   totval      True  DOUBLE PRECISION
8   totcnt      True  DOUBLE PRECISION
9   usdval      True  DOUBLE PRECISION
10  usdcnt      True  DOUBLE PRECISION

In [11]:
db.describe_table(library='ff', table='factors_monthly')

Approximately 1136 rows in ff.factors_monthly.

     name  nullable              type
0    date      True              DATE
1   mktrf      True  DOUBLE PRECISION
2     smb      True  DOUBLE PRECISION
3     hml      True  DOUBLE PRECISION
4      rf      True  DOUBLE PRECISION
5    year      True  DOUBLE PRECISION
6   month      True  DOUBLE PRECISION
7     umd      True  DOUBLE PRECISION
8  dateff      True              DATE

In [12]:
import pandas as pd
import numpy as np

In [13]:
rf = db.get_table(library='ff', table='factors_monthly')[['date', 'rf']]
rf['date'] = rf['date'] - pd.tseries.offsets.MonthEnd()

In [14]:
rf.head()

        date      rf
0 1926-06-30  0.0022
1 1926-07-31  0.0025
2 1926-08-31  0.0023
3 1926-09-30  0.0032
4 1926-10-31  0.0031

In [16]:
mkt = db.get_table(library='crsp', table='msi')[['date', 'vwretd', 'vwretx']]
mkt['date'] = mkt['date']-pd.tseries.offsets.MonthEnd()

In [17]:
mkt.head()

        date    vwretd    vwretx
0 1925-11-30       NaN       NaN
1 1925-12-31  0.000561 -0.001395
2 1926-01-31 -0.033046 -0.036587
3 1926-02-28 -0.064002 -0.070021
4 1926-03-31  0.037029  0.034043

In [18]:
df=pd.merge(mkt, rf, on='date')
df.head()

        date    vwretd    vwretx      rf
0 1926-06-30  0.031411  0.029224  0.0022
1 1926-07-31  0.028647  0.025358  0.0025
2 1926-08-31  0.005787  0.000030  0.0023
3 1926-09-30 -0.028996 -0.031069  0.0032
4 1926-10-31  0.028554  0.022979  0.0031

In [19]:
df['DP']=df['vwretd']-df['vwretx']
df['DP_lag']=df['DP'].shift(1)

In [20]:
df['exret']=df['vwretd']-df['rf']
df.head()

        date    vwretd    vwretx      rf        DP    DP_lag     exret
0 1926-06-30  0.031411  0.029224  0.0022  0.002186       NaN  0.029211
1 1926-07-31  0.028647  0.025358  0.0025  0.003290  0.002186  0.026147
2 1926-08-31  0.005787  0.000030  0.0023  0.005757  0.003290  0.003487
3 1926-09-30 -0.028996 -0.031069  0.0032  0.002073  0.005757 -0.032196
4 1926-10-31  0.028554  0.022979  0.0031  0.005575  0.002073  0.025454

In [21]:
df.date=df.date.astype(str)
df[['year', 'month', 'day']] = df.date.str.split("-", expand=True)
df.year = df.year.astype(int)
df=df[df.year<2021]

In [22]:
regression_data = df[['date', 'DP_lag', 'exret']]

In [23]:
regression_data=regression_data.dropna()
regression_data.head()

         date    DP_lag     exret
1  1926-07-31  0.002186  0.026147
2  1926-08-31  0.003290  0.003487
3  1926-09-30  0.005757 -0.032196
4  1926-10-31  0.002073  0.025454
5  1926-11-30  0.005575  0.026411

In [24]:
import statsmodels.formula.api as sm

In [25]:
result = sm.ols(formula="exret ~ DP_lag", data=regression_data).fit()

In [26]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  exret   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     2.764
Date:                Mon, 19 Apr 2021   Prob (F-statistic):             0.0967
Time:                        16:45:10   Log-Likelihood:                 1710.0
No. Observations:                1133   AIC:                            -3416.
Df Residuals:                    1131   BIC:                            -3406.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0028      0.003      1.004      0.316      -0.003       0.008
DP_lag         1.2571      0.756      1.663      0.097      -0.227       2.741
==============================================================================
Omnibus:                      179.512   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2681.580
Skew:                           0.129   Prob(JB):                         0.00
Kurtosis:                      10.532   Cond. No.                         475.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [27]:
reg = sm.ols(formula="exret ~ DP_lag", data=regression_data).fit()
new = reg.get_robustcov_results(cov_type='HAC', maxlags=12)
print(new.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  exret   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                  0.002
Method:                 Least Squares   F-statistic:                     2.512
Date:                Mon, 19 Apr 2021   Prob (F-statistic):              0.113
Time:                        16:45:15   Log-Likelihood:                 1710.0
No. Observations:                1133   AIC:                            -3416.
Df Residuals:                    1131   BIC:                            -3406.
Df Model:                           1
Covariance Type:                  HAC
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0028      0.003      1.103      0.270      -0.002       0.008
DP_lag         1.2571      0.793      1.585      0.113      -0.299       2.813
==============================================================================
Omnibus:                      179.512   Durbin-Watson:                   1.795
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2681.580
Skew:                           0.129   Prob(JB):                         0.00
Kurtosis:                      10.532   Cond. No.                         475.
==============================================================================

Warnings:
[1] Standard Errors are heteroscedasticity and autocorrelation robust (HAC) using 12 lags and without small sample correction

In [28]:
import os
regression_data.to_csv('regression_data.csv')